import type { UiLanguage } from './index'

/**
 * Static UI copy: labels, headings, hints, placeholders and option text that
 * live in the view layer. One entry per user-visible string, always complete
 * across every supported language.
 */
export const viewMessages: Record<string, Record<UiLanguage, string>> = {
  noExportableSummary: { 'zh-TW': '沒有可匯出的摘要內容。', 'zh-CN': '没有可导出的摘要内容。', en: 'There is no summary content to export.', ja: 'エクスポート可能な要約内容がありません。', de: 'Kein exportierbarer Zusammenfassungsinhalt vorhanden.' },
  downloadPickFailed: { 'zh-TW': '下載失敗', 'zh-CN': '下载失败', en: 'Download failed', ja: 'ダウンロードに失敗しました', de: 'Download fehlgeschlagen' },
  modelHealthHealthy: { 'zh-TW': '健康', 'zh-CN': '健康', en: 'Healthy', ja: '正常', de: 'Einwandfrei' },
  modelHealthDegraded: { 'zh-TW': '降級', 'zh-CN': '降级', en: 'Degraded', ja: '劣化', de: 'Eingeschränkt' },
  modelHealthFailed: { 'zh-TW': '失敗', 'zh-CN': '失败', en: 'Failed', ja: '失敗', de: 'Fehlgeschlagen' },
  modelHealthUnknown: { 'zh-TW': '未確認', 'zh-CN': '未确认', en: 'Unknown', ja: '未確認', de: 'Unbekannt' },
  modelHealthNotChecked: { 'zh-TW': '尚未執行健康檢查', 'zh-CN': '尚未执行健康检查', en: 'Health check has not run yet', ja: '健康チェックはまだ実行されていません', de: 'Der Gesundheitstest wurde noch nicht ausgeführt.' },
  modelApiKeySaveFailed: { 'zh-TW': '模型設定已更新，但 API key 保存失敗。', 'zh-CN': '模型设置已更新，但 API key 保存失败。', en: 'Model settings were updated, but the API key could not be saved.', ja: 'モデル設定は更新されましたが、API キーの保存に失敗しました。', de: 'Die Modelleinstellungen wurden aktualisiert, aber der API-Schlüssel konnte nicht gespeichert werden.' },
  asrModelSwitchSaveFailed: { 'zh-TW': 'ASR 模型已切換，但設定檔保存失敗。', 'zh-CN': 'ASR 模型已切换，但配置文件保存失败。', en: 'The ASR model was switched, but saving the settings file failed.', ja: 'ASR モデルは切り替わりましたが、設定ファイルの保存に失敗しました。', de: 'Das ASR-Modell wurde gewechselt, aber das Speichern der Einstellungsdatei ist fehlgeschlagen.' },
  asrModelSwitchApplied: { 'zh-TW': '已切換 ASR 模型；下次開始收音生效。', 'zh-CN': '已切换 ASR 模型；下次开始录音生效。', en: 'ASR model switched; it takes effect the next time recording starts.', ja: 'ASR モデルを切り替えました。次の録音開始時に有効になります。', de: 'ASR-Modell gewechselt; wirkt ab der nächsten Aufnahme.' },
  recordTranscriptAria: { 'zh-TW': '{title} 逐字稿', 'zh-CN': '{title} 文字稿', en: 'Transcript of {title}', ja: '{title} の文字起こし', de: 'Transkript von {title}' },
  unknownMediaType: { 'zh-TW': '未知格式', 'zh-CN': '未知格式', en: 'Unknown format', ja: '不明な形式', de: 'Unbekanntes Format' },
  voiceprintOr: { 'zh-TW': '或', 'zh-CN': '或', en: 'or', ja: 'または', de: 'oder' },
  pcm16WavMinimum: { 'zh-TW': 'PCM16 WAV · 最少 1 秒', 'zh-CN': 'PCM16 WAV · 最少 1 秒', en: 'PCM16 WAV · 1 s minimum', ja: 'PCM16 WAV · 最低 1 秒', de: 'PCM16 WAV · mind. 1 s' },
  labelColon: { 'zh-TW': '：', 'zh-CN': '：', en: ': ', ja: '：', de: ': ' },
  labelDash: { 'zh-TW': '－', 'zh-CN': '－', en: ' – ', ja: '－', de: ' – ' },
  pageSeparator: { 'zh-TW': '／', 'zh-CN': '／', en: ' / ', ja: '／', de: ' / ' },
  refreshAudioSourcesFailed: { 'zh-TW': '無法重新整理音源裝置', 'zh-CN': '无法刷新音频设备', en: 'Could not refresh audio devices', ja: '音源デバイスを更新できませんでした', de: 'Audioquellen konnten nicht aktualisiert werden' },
  enableSpeakerDiarization: { 'zh-TW': '啟用語者分離', 'zh-CN': '启用说话人分离', en: 'Enable speaker diarization', ja: '話者分離を有効にする', de: 'Sprechertrennung aktivieren' },
  glossaryJsonImported: { 'zh-TW': '已載入 {count} 筆 JSON 術語{invalid}{duplicates}；請儲存設定。', 'zh-CN': '已加载 {count} 条 JSON 术语{invalid}{duplicates}；请保存设置。', en: 'Loaded {count} glossary terms from JSON{invalid}{duplicates}; save your settings.', ja: '{count} 件の JSON 用語を読み込みました{invalid}{duplicates}。設定を保存してください。', de: '{count} Glossarbegriffe aus JSON geladen{invalid}{duplicates}; Einstellungen speichern.' },
  glossaryJsonSkippedInvalid: { 'zh-TW': '；略過 {count} 筆無效資料', 'zh-CN': '；跳过 {count} 条无效数据', en: '; skipped {count} invalid entries', ja: '、無効な項目 {count} 件をスキップ', de: '; {count} ungültige Einträge übersprungen' },
  glossaryJsonSkippedDuplicates: { 'zh-TW': '；略過 {count} 筆重複或超出上限資料', 'zh-CN': '；跳过 {count} 条重复或超出上限数据', en: '; skipped {count} duplicate or over-limit entries', ja: '、重複または上限超過の項目 {count} 件をスキップ', de: '; {count} doppelte oder über dem Limit liegende Einträge übersprungen' },
  denoiseSavedNewStream: { 'zh-TW': '降噪偏好已保存；需切換麥克風或下次開始收音才會建立新的音源 stream。', 'zh-CN': '降噪偏好已保存；需切换麦克风或下次开始录音才会创建新的音频流。', en: 'Noise-suppression preference saved; a new media stream is created when you switch microphones or start the next recording.', ja: 'ノイズ抑制の設定を保存しました。マイクを切り替えるか、次の録音を開始すると新しい音声ストリームが作成されます。', de: 'Rauschunterdrückung gespeichert; ein neuer Medienstrom wird beim Wechsel des Mikrofons oder bei der nächsten Aufnahme erstellt.' },
  kaiserResample: { 'zh-TW': '使用 Kaiser 高品質重取樣', 'zh-CN': '使用 Kaiser 高质量重采样', en: 'Use high-quality Kaiser resampling', ja: '高品質 Kaiser リサンプリングを使用', de: 'Hochwertiges Kaiser-Resampling verwenden' },
  nextRecordingApplies: { 'zh-TW': '下一次收音生效', 'zh-CN': '下次录音生效', en: 'Takes effect on the next recording', ja: '次の録音から有効', de: 'Gilt ab der nächsten Aufnahme' },
  useSileroVad: { 'zh-TW': '使用 Silero VAD', 'zh-CN': '使用 Silero VAD', en: 'Use Silero VAD', ja: 'Silero VAD を使用', de: 'Silero VAD verwenden' },
  useDynaudnorm: { 'zh-TW': '使用 dynaudnorm 音量正規化', 'zh-CN': '使用 dynaudnorm 音量标准化', en: 'Use dynaudnorm volume normalization', ja: 'dynaudnorm 音量正規化を使用', de: 'dynaudnorm-Lautstärkenormalisierung verwenden' },
  webGatewayCpuWorkerHint: { 'zh-TW': 'Web gateway CPU worker；下一次收音生效', 'zh-CN': 'Web gateway CPU worker；下次录音生效', en: 'Web gateway CPU worker; takes effect on the next recording', ja: 'Web gateway CPU worker、次の録音から有効', de: 'Web-Gateway-CPU-Worker; gilt ab der nächsten Aufnahme' },
  sileroVadNotLoaded: { 'zh-TW': 'Silero VAD 模型尚未載入（模型檔、checksum 或 onnxruntime-node 檢查未通過），因此不顯示啟用選項。', 'zh-CN': 'Silero VAD 模型尚未加载（模型文件、checksum 或 onnxruntime-node 检查未通过），因此不显示启用选项。', en: 'The Silero VAD model is not loaded yet (the model file, checksum, or onnxruntime-node check failed), so the enable option is hidden.', ja: 'Silero VAD モデルはまだ読み込まれていません（モデルファイル、checksum、onnxruntime-node のチェック未通過）。そのため有効化オプションは表示されません。', de: 'Das Silero-VAD-Modell ist noch nicht geladen (Modelldatei, Checksumme oder onnxruntime-node-Prüfung nicht bestanden), daher wird die Aktivierungsoption nicht angezeigt.' },
  sileroVadHealth: { 'zh-TW': 'Silero VAD 健康度', 'zh-CN': 'Silero VAD 健康度', en: 'Silero VAD health', ja: 'Silero VAD の健全性', de: 'Silero-VAD-Status' },
  noiseSuppressionAdvancedHint: { 'zh-TW': '此設定請求瀏覽器的 noiseSuppression，只影響新建或切換的麥克風 stream；保存音檔與送往 ASR 的音訊都使用同一處理後 stream。瀏覽器可能不支援此約束。', 'zh-CN': '此设置请求浏览器的 noiseSuppression，只影响新建或切换的麦克风流；保存音频和送往 ASR 的音频都使用同一个处理后的流。浏览器可能不支持此约束。', en: 'This setting requests the browser’s noiseSuppression and only affects newly created or switched microphone streams; saved audio and audio sent to the ASR use that same processed stream. The browser may not support this constraint.', ja: 'この設定はブラウザーの noiseSuppression を要求し、新規作成または切り替え時のマイクストリームにのみ影響します。保存される音声と ASR に送信される音声は同じ処理済みストリームを使用します。ブラウザーがこの制約に対応していない場合があります。', de: 'Diese Einstellung fordert die noiseSuppression des Browsers an und betrifft nur neu erstellte oder gewechselte Mikrofon-Streams; gespeichertes Audio und an die ASR gesendetes Audio verwenden denselben verarbeiteten Stream. Der Browser unterstützt diese Einschränkung möglicherweise nicht.' },
  kaiserResampleAdvancedHint: { 'zh-TW': '只會套用在送往 ASR 的重取樣分支，原始錄音與聲紋 embedding 保持未正規化；開啟後會使用較高品質的 anti-alias filter。', 'zh-CN': '只会应用在送往 ASR 的重采样分支，原始录音与声纹 embedding 保持未标准化；开启后会使用更高质量的 anti-alias filter。', en: 'Applied only to the resampling path that feeds the ASR; the original recording and voiceprint embedding stay unnormalized. When enabled, a higher-quality anti-alias filter is used.', ja: 'ASR に送信されるリサンプリング処理にのみ適用されます。元の録音と声紋 embedding は正規化されません。有効にすると高品質な anti-alias フィルターを使用します。', de: 'Wird nur auf den Resampling-Pfad zur ASR angewendet; die Originalaufnahme und das Stimmabdruck-Embedding bleiben unnormiert. Bei Aktivierung wird ein hochwertiger Anti-Alias-Filter verwendet.' },
  silenceStartAdvancedHint: { 'zh-TW': '預設值採 faster-whisper 常用的 500 ms 靜音起點；Breeze HTTP 的時間戳是 App 音訊 chunk 邊界，不是模型 word timestamps。', 'zh-CN': '默认值采用 faster-whisper 常用的 500 ms 静音起点；Breeze HTTP 的时间戳是 App 音频 chunk 边界，不是模型 word timestamps。', en: 'The default uses the 500 ms silence onset common in faster-whisper; Breeze HTTP timestamps are app audio chunk boundaries, not model word timestamps.', ja: '既定値は faster-whisper で一般的な 500 ms の無音開始を使用します。Breeze HTTP のタイムスタンプは App 音声チャンクの境界であり、モデルの単語タイムスタンプではありません。', de: 'Der Standardwert verwendet den in faster-whisper üblichen 500-ms-Schweigebeginn; die Breeze-HTTP-Zeitstempel sind App-Audio-Chunk-Grenzen, keine Modell-Wortzeitstempel.' },
  glossaryHelp: { 'zh-TW': '支援 {「術語」:「指定譯法」} 或 [{"term":"術語","translation":"指定譯法"}]；載入後請儲存設定。', 'zh-CN': '支持 {“术语”：“指定译法”} 或 [{"term":"术语","translation":"指定译法"}]；加载后请保存设置。', en: 'Supports {"term":"preferred translation"} or [{"term":"term","translation":"preferred translation"}]. Save your settings after loading.', ja: '{"用語":"指定訳"} または [{"term":"用語","translation":"指定訳"}] に対応しています。読み込み後に設定を保存してください。', de: 'Unterstützt {"Begriff":"bevorzugte Übersetzung"} oder [{"term":"Begriff","translation":"bevorzugte Übersetzung"}]. Speichern Sie die Einstellungen nach dem Laden.' },
  summaryTranslationFailed: { 'zh-TW': '摘要翻譯失敗', 'zh-CN': '摘要翻译失败', en: 'Summary translation failed', ja: '要約の翻訳に失敗しました', de: 'Zusammenfassungsübersetzung fehlgeschlagen' }
}
