import { useState, type FormEvent, type ReactElement } from 'react'
import type { AuthState } from '../hooks/useAuth'

type AuthActions = { login: (input: { username: string; password: string }) => Promise<void>; register: (input: { username: string; password: string; NT: string; Department: string }) => Promise<void>; setError: (message: string) => void }

export function AuthGate({ auth }: { auth: AuthState & AuthActions }): ReactElement {
  const [mode, setMode] = useState<'login' | 'register'>('login'); const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [NT, setNT] = useState(''); const [Department, setDepartment] = useState(''); const [submitting, setSubmitting] = useState(false)
  const submit = async (event: FormEvent): Promise<void> => { event.preventDefault(); setSubmitting(true); auth.setError(''); try { if (mode === 'login') await auth.login({ username, password }); else await auth.register({ username, password, NT, Department }) } catch (error) { auth.setError(error instanceof Error ? error.message : '登入失敗') } finally { setSubmitting(false) } }
  if (auth.status === 'checking') return <main className="auth-screen"><p>正在確認登入狀態…</p></main>
  return <main className="auth-screen"><section className="auth-card"><p className="eyebrow">S2T UI</p><h1>{mode === 'login' ? '登入' : '建立帳號'}</h1><p className="hint">登入後，你的紀錄、設定與術語將依帳號分開保存。</p><form onSubmit={(event) => void submit(event)}><label>帳號<input autoComplete="username" value={username} onChange={(event) => setUsername(event.target.value)} required /></label><label>密碼<input type="password" autoComplete={mode === 'login' ? 'current-password' : 'new-password'} value={password} onChange={(event) => setPassword(event.target.value)} required /></label>{mode === 'register' && <><label>NT<input value={NT} onChange={(event) => setNT(event.target.value)} required /></label><label>Department<input value={Department} onChange={(event) => setDepartment(event.target.value)} required /></label></>}{auth.error && <p className="import-error" role="alert">{auth.error}</p>}<button className="primary" disabled={submitting}>{submitting ? '處理中…' : mode === 'login' ? '登入' : '註冊並登入'}</button></form><button className="text-button" onClick={() => { setMode((current) => current === 'login' ? 'register' : 'login'); auth.setError('') }}>{mode === 'login' ? '還沒有帳號？建立帳號' : '已有帳號？返回登入'}</button></section></main>
}
