const fs=require('node:fs'),crypto=require('node:crypto');
const base=process.env.S2T_TEST_BASE_URL || 'http://test-ingress:8080';
if (!['http://test-ingress:8080','http://gateway:8787'].includes(base)) throw new Error('Load target must be an isolated test service');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const wav=Buffer.alloc(48044);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(16000,24);wav.writeUInt32LE(32000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(wav.length-44,40);for(let i=44;i<wav.length;i+=2)wav.writeInt16LE(Math.round(8000*Math.sin(i*0.04)),i);
async function call(user,path,options={}){const r=await fetch(base+path,{...options,headers:{...(user?{authorization:'Bearer '+user.token}:{}),...options.headers},signal:AbortSignal.timeout(30000)});const raw=Buffer.from(await r.arrayBuffer());let body;try{body=JSON.parse(raw)}catch{}return{status:r.status,body,raw};}
const json=body=>({method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});
function check(r,expected,context){if(r.status!==expected)throw Error(context+': '+r.status+' '+JSON.stringify(r.body));return r.body;}
async function mapLimit(items,n,fn){let next=0;await Promise.all(Array.from({length:n},async()=>{while(next<items.length){const i=next++;await fn(items[i],i)}}));}
const mode=process.argv[2],file='/tmp/stress-users.json';
(async()=>{
if(mode==='register'){const users=[],prefix='stress'+Date.now();await mapLimit(Array.from({length:100}),5,async(_,i)=>{const body=check(await call(null,'/api/auth/register',json({username:prefix+'_'+i,password:'stress-password-test-only',NT:'Stress'+i,Department:'LoadLab'})),201,'register');users[i]=body;});fs.writeFileSync(file,JSON.stringify(users),{mode:0o600});console.log(JSON.stringify({phase:mode,users:users.length,distinctIds:new Set(users.map(u=>u.user.id)).size}));return;}
const users=JSON.parse(fs.readFileSync(file));
if(mode==='load'){
 const name=process.argv[3],count=Number(process.argv[4]||100),seconds=Number(process.argv[5]||60),interval=Number(process.argv[6]||1500);
 const start=Date.now(),end=start+seconds*1000,metrics={startedAt:new Date(start).toISOString(),phase:name,baseUrl:base,users:count,seconds,intervalMs:interval,scheduled:0,dropped:0,asr:{},translation:{},chains:0,failedChains:0,errors:[],peakPending:0,schedulerLagMaxMs:0,timeline:[]},samples={asr:[],translation:[],chain:[]};let pending=0;const tasks=new Set();
 async function request(u,route,opts,kind){const t=Date.now();try{const r=await call(u,route,opts);metrics[kind][r.status]=(metrics[kind][r.status]||0)+1;if(r.status===200)samples[kind].push(Date.now()-t);else if(metrics.errors.length<8)metrics.errors.push({kind,status:r.status,message:r.body?.error});return r;}catch(e){metrics[kind].network=(metrics[kind].network||0)+1;if(metrics.errors.length<8)metrics.errors.push({kind,message:e.message});return{status:0}}}
 async function chain(i,tick){pending++;metrics.peakPending=Math.max(metrics.peakPending,pending);const t=Date.now(),u=users[i],key=name+'-'+start+'-'+i+'-'+tick;try{const a=await request(u,'/api/transcriptions',{method:'POST',headers:{'content-type':'audio/wav','x-s2t-idempotency-key':key+'-asr'},body:wav},'asr');if(a.status!==200){metrics.failedChains++;return;}const tr=await request(u,'/api/translations',{...json({text:a.body.text,sourceLanguage:'en',targetLanguage:'zh-TW'}),headers:{'content-type':'application/json','x-s2t-idempotency-key':key+'-tr'}},'translation');if(tr.status===200){metrics.chains++;samples.chain.push(Date.now()-t)}else metrics.failedChains++;}finally{pending--;}}
 let next=0;const total=Math.floor(seconds*1000/interval)*count;const timer=setInterval(()=>metrics.timeline.push({second:Math.floor((Date.now()-start)/1000),pending,chains:metrics.chains,failed:metrics.failedChains}),1000);
 while(next<total){const due=start+Math.floor(next/count)*interval+(next%count)*interval/count;await sleep(Math.max(0,due-Date.now()));metrics.schedulerLagMaxMs=Math.max(metrics.schedulerLagMaxMs,Date.now()-due);const i=next%count,tick=Math.floor(next/count);next++;metrics.scheduled++;if(pending>=1000){metrics.dropped++;continue;}const p=chain(i,tick);tasks.add(p);p.finally(()=>tasks.delete(p));}
 await Promise.all(tasks);clearInterval(timer);metrics.elapsedMs=Date.now()-start;for(const[k,a]of Object.entries(samples)){a.sort((a,b)=>a-b);metrics[k+'LatencyMs']={n:a.length,p50:a[Math.floor(a.length*.5)]||0,p95:a[Math.floor(a.length*.95)]||0,p99:a[Math.floor(a.length*.99)]||0,max:a.at(-1)||0};}console.log(JSON.stringify(metrics));return;
}
if(mode==='storage'){
const results=[],started=Date.now();await mapLimit(users,20,async(u,i)=>{const id='rec-'+u.user.id,key='audio-'+u.user.id;try{
 for(let c=0;c<3;c++)check(await call(u,`/api/data/recordings/${id}/chunks/${c}`,{method:'PUT',headers:{'content-type':'application/octet-stream','x-s2t-start-sample':String(c*24000),'x-s2t-sample-rate':'16000'},body:wav.subarray(44)}),200,'chunk');
 check(await call(u,`/api/data/recordings/${id}/chunks/0`,{method:'PUT',headers:{'x-s2t-start-sample':'0','x-s2t-sample-rate':'16000'},body:wav.subarray(44)}),200,'same chunk retry');
 check(await call(u,`/api/data/recordings/${id}/finish`,json({totalChunks:3,totalSamples:72000})),200,'finish');
 check(await call(u,`/api/data/recordings/${id}/promote`,json({audioKey:key})),201,'promote');
 const session={id:'sess-'+u.user.id,audioKey:key,durationMs:4500,processingToken:'test-'+i,processingState:'running',processingStage:'diarization',segments:[{id:'seg1',status:'final',startMs:0,endMs:1500,sourceText:'simulated speech',translatedText:'模擬翻譯',speaker:''}]};
 check(await call(u,'/api/data/sessions',json({sessions:[session],version:0})),200,'save');
 check(await call(u,'/api/data/sessions',json({sessions:[session],version:0})),409,'stale CAS');
 const audio=await call(u,'/api/data/audio/'+key);check(audio,200,'audio read');const expected=Buffer.concat([wav.subarray(44),wav.subarray(44),wav.subarray(44)]);if(!audio.raw.subarray(44).equals(expected))throw Error('PCM integrity mismatch');
 const other=users[(i+1)%users.length];const denied=await call(other,'/api/data/audio/'+key);if(![403,404].includes(denied.status))throw Error('tenant isolation '+denied.status);
 const job=check(await call(u,'/api/data/diarization-jobs',json({sessionId:session.id,audioKey:key,processingToken:session.processingToken})),202,'enqueue').job;
 results[i]={i,ok:true,bytes:audio.raw.length,sha256:crypto.createHash('sha256').update(audio.raw).digest('hex'),jobId:job.id};
}catch(e){results[i]={i,ok:false,error:e.message}}});
fs.writeFileSync('/tmp/storage-results.json',JSON.stringify(results));console.log(JSON.stringify({phase:mode,elapsedMs:Date.now()-started,passed:results.filter(r=>r.ok).length,results}));return;
}
if(mode==='jobs'){const records=JSON.parse(fs.readFileSync('/tmp/storage-results.json')),deadline=Date.now()+180000;let output;do{output=[];await mapLimit(records.filter(r=>r.ok),20,async(r)=>{const j=await call(users[r.i],'/api/data/diarization-jobs?id='+r.jobId);const s=await call(users[r.i],'/api/data/sessions');output.push({i:r.i,state:j.body?.job?.state,status:j.body?.job?.status,error:j.body?.job?.error,sessionState:s.body?.sessions?.[0]?.processingState,speaker:s.body?.sessions?.[0]?.segments?.[0]?.speaker,translation:s.body?.sessions?.[0]?.segments?.[0]?.translatedText});});if(output.every(x=>x.sessionState==='completed'))break;await sleep(2000);}while(Date.now()<deadline);console.log(JSON.stringify({phase:mode,completed:output.filter(x=>x.sessionState==='completed'&&x.speaker==='SPEAKER_01'&&x.translation==='模擬翻譯').length,results:output}));return;}
if(mode==='voiceprints'){const results=[];await mapLimit(users,10,async(u,i)=>{try{const r=check(await call(u,'/api/voiceprints',{method:'POST',headers:{'content-type':'audio/wav'},body:wav}),201,'enroll');const list=check(await call(u,'/api/voiceprints'),200,'list');if(!list.voiceprints.some(v=>v.id===r.voiceprint.id))throw Error('missing metadata');const search=check(await call(u,'/api/voiceprints/identify',{method:'POST',headers:{'content-type':'audio/wav'},body:wav}),200,'search');if(search.match?.id!==r.voiceprint.id)throw Error('wrong search match');results[i]={i,ok:true,id:r.voiceprint.id};}catch(e){results[i]={i,ok:false,error:e.message}}});console.log(JSON.stringify({phase:mode,passed:results.filter(r=>r.ok).length,results}));return;}
throw Error('unknown mode');
})().catch(e=>{console.error(e);process.exit(1)});
